// Generated by CoffeeScript 1.4.0
var hostStateModule, should, state;

should = require("should");
myLocalIP = require("my-local-ip");

hostname = require("../../../src/hostname");

describe("properHostname", function() {
  it('returns local ip if hostname equals to localhost', function() {
    return hostname.properHostname('localhost').should.equal(myLocalIP());
  });

  it('returns local ip if hostname equals to 127.0.0.1', function() {
    return hostname.properHostname('127.0.0.1').should.equal(myLocalIP());
  });

  it('returns hostname if hostname is something else', function() {
    return hostname.properHostname('foresee.com').should.equal('foresee.com');
  });

  it('preserve port in hostname', function() {
    return hostname.properHostname('foresee.com:3000').should.equal('foresee.com:3000');
  });

  it('preserve port after replacing it with new hostname', function() {
    return hostname.properHostname('localhost:3000').should.equal(myLocalIP() + ":3000");
  });
});
