// Generated by CoffeeScript 1.4.0
var assert, expect;

expect = chai.expect;

assert = chai.assert;

describe("index", function() {
  return describe("room name", function() {
    it("should denied blank", function() {
      var result;
      result = validateRoomName("");
      return assert.isFalse(result);
    });
    return it("should not allow sharp in roomname", function() {
      var result;
      result = validateRoomName("#");
      return assert.isFalse(result);
    });
  });
});
