// Generated by CoffeeScript 1.4.0
var DataStore, cache, datastore, hostStateModule, hoststate;

cache = require('memory-cache');

hostStateModule = require("../src/hoststate");

hoststate = hostStateModule.hoststate;

DataStore = function(storage) {
  return {
    get: function(roomName) {
      if (!(storage.get(roomName) != null)) {
        storage.put(roomName, {
          stories: {},
          participants: {},
          state: hoststate.INITIAL
        });
      }
      return storage.get(roomName);
    },
    put: function(roomName, data) {
      return storage.put(roomName, data);
    },
    clear: function() {
      return storage.clear();
    }
  };
};

datastore = DataStore(cache);

exports.datastore = datastore;

exports.cache = cache;
