// Generated by CoffeeScript 1.4.0
var ECT, app, assets, clientSockets, core, ectRenderer, express, getSocketUrl, io, route, sendRefreshMessage, server;

express = require('express');

assets = require('connect-assets');

app = express();

ECT = require('ect');

ectRenderer = ECT({
  cache: false,
  watch: false,
  root: __dirname + '/../views'
});

server = require('http').createServer(app);

server.port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

app.use(assets());

app.use(express["static"](process.cwd() + '/public'));

app.engine('.ect', ectRenderer.render);

core = require("./core").core;

route = require("./route").route;

var socketio = require('socket.io').listen(server, {
  'log level': 1
});

var websocket = require("./websocket").websocket(socketio, core);


getSocketUrl = function(req) {
  return "http://" + req.headers.host;
};

app.get('/host/:id', function(req, res) {
  return res.render('host.ect', {
    title: "Host - " + req.params.id,
    url: "http://" + properHostname(req.headers.host) + "/join/" + req.params.id,
    socketUrl: getSocketUrl(req),
    roomId: req.params.id
  });
});

app.get('/story/add/room/:room/story/:story', route.addStory);

app.get('/stories/:room', route.listStories);

app.get('/join/:id', route.join);

app.get('/', route.index);

app.get('/join/room/:room/name/:name', route.joinRoom(websocket));

module.exports = server;

module.exports.route = route;

function properHostname(host){
  if( host.match(/(localhost|127(\.0){2}\.1)/) ) {
      return require('my-local-ip')();
  }

  return host;
}
