// Generated by CoffeeScript 1.4.0
var core, getSocketUrl, route;

core = require("./core").core;

getSocketUrl = function(req) {
  return "http://" + req.headers.host;
};

route = {
  index: function(req, res) {
    return res.render('index.ect', {
      title: "Foresee"
    });
  },
  join: function(req, res) {
    return res.render('join.ect', {
      id: req.params.id,
      socketUrl: getSocketUrl(req)
    });
  },
  addStory: function(req, res) {
    core.addStory(req.params.room, req.params.story);
    return res.send(core.listStories(req.params.room));
  }
};

exports.route = route;
