// Generated by CoffeeScript 1.4.0
var assert, expect, mockJqueryVal;

expect = chai.expect;

assert = chai.assert;

mockJqueryVal = function(jq, selector, retVal) {
  return jq.withArgs(selector).returns({
    val: function() {
      return retVal;
    }
  });
};

describe("QRCtrl", function() {
  return it("generate QR Code from Element on page", function() {
    var aUrl, jq, qrCodeLib, qrCtrl;
    aUrl = "anyValidUrl";
    jq = sinon.stub();
    mockJqueryVal(jq, "#url", aUrl);
    qrCodeLib = sinon.stub();
    qrCtrl = QRCtrl(jq, qrCodeLib);
    qrCtrl.generateQRCode();
    return assert.isTrue(qrCodeLib.calledWith("qrcode", aUrl), "qrcodeLib not called with correct parameters");
  });
});
